yum install curl -y 
curl http://169.254.169.254/latest/meta-data/placement/availability-zone

tasks:
    - name: Copy of the local remote file
      copy:
        src: /tmp/test.test
        dest: /tmp
