---
host: localhost

tasks:
    - name: Get the current region availability
      shell: curl http://169.254.169.254/latest/meta-data/placement/availability-zone
    
    - name: Copy of the local remote file
      copy:
        src: /mycompany-services.tar.gz
        dest: /temp
    - name: Extract mycompany-services.tar.gz into /data
      unarchive:
        src: /temp
        dest: /data

    - name: Start service docker and tomcat, if not started
      service:
        name: docker
        state: started
      service:
        name: tomcat
        state: started
