---
host: localhost
become: yes
become_user: root
tasks:

  # - name: Upgrade all packages
  #   yum:
  #     name: '*'
  #     state: latest
  #
  # - name: Install following packages
  #   yum:
  #     name: "{{ packages }}"
  #     vars:
  #       packages:
  #         - tomcat
  #         - python3
  #         - python3-pip
  #         - docker-engine
  #         - git
  #         - curl

  - name: take metadata from the instance
    shell: http://169.254.169.254/latest/meta-data/placement/availability_zone.

  # - name: Copy of the local remote file
  #   copy:
  #     src: /mycompany-services.tar.gz
  #     dest: /tmp
  #
  # - name: Extract mycompany-services.tar.gz into /data
  #   unarchive:
  #     src: /tmp
  #     dest: /data
  #
  # - name: Start service docker and tomcat, if not started
  #   service:
  #     name: docker
  #     state: started
  #
  #   service:
  #     name: tomcat
  #     state: started
